### ISSUE TITLE
[meta] Deis Operator UX Theme

### ISSUE THREAD

**Issue by slack** [deis/workflow#130]
Milestone: v2.0-beta2

## Installation / Configuration

As an operator, I should be able to quickly configure object storage
consistently across Deis Workflow when running `helm install deis/workflow-...`

Most of the work is described and tracked in: https://github.com/deis/deis/issues/4966

Scenarios to test and validate:
* On-cluster: minio, default
* Off-cluster: AWS
    * Bucket in us-east-1 (s3 us-standard)
    * Bucket in us-west-2 (s3 regional endpoint)
* Off-cluster: GCS ~~w/ S3 compat mode~~
    * us-central1-x
    * us-east1-x
* [X] Bucket for database backups `slug_bucket`
* [X] Bucket for slugs `slug_bucket`
* [X] Bucket for registry `registry_bucket`

## Recoverability

Operators need to have confidence that they can recover from cluster disasters.
We need to test and validate cluster recovery from off-cluster object storage
to working platform.

Reproducible Helm charts: https://github.com/deis/charts/issues/199

Given a set of buckets, used by a previous installation of the platform. An
Operator should be able to quickly recover their instance of Deis Workflow.

Assumes a brand-new k8s cluster, with no conflicting or lingering application
namespaces.

This should be tested on both S3 and GCS-backed clusters.

## Champagne

Learn by doing! We need to host our own applications. First two applications
are deis slack inviter and workflow-manager API backend.

https://github.com/deis/deployment/issues/8

## Delivery Process

@sgoings details here!

**Comment by kmala** [comment]
Since we merged the object store PR's we should be testing GCS directly and not in compat mode

**Comment by slack** [comment]
@kmala cool, will update.

**Comment by mboersma** [comment]
Object storage configuration was (mostly) fixed up for beta2, and the recoverability targets are a focus for beta3. I'm closing this issue so the beta2 milestone can be closed, but if I missed something please do add it on for the next beta release.
