### ISSUE TITLE
Meta[Swift]: Add support for swift object storage

### ISSUE THREAD

**Issue by kmala** [deis/workflow#306]
To add support for new object storage requires changes to various components in the workflow.This is a meta issue to track all the changes required.
  - [x] [deis/builder](https://github.com/deis/builder): https://github.com/deis/builder/pull/366
  - [x] [deis/slugbuilder](https://github.com/deis/slugbuilder): https://github.com/deis/slugbuilder/pull/84
  - [x] [deis/slugrunner](https://github.com/deis/slugrunner): https://github.com/deis/slugrunner/pull/44
  - [x] [deis/postgres](https://github.com/deis/postgres): https://github.com/deis/postgres/pull/106
  - [x] [deis/charts](https://github.com/deis/charts): https://github.com/deis/charts/pull/290
  - [x] [deis/registry](https://github.com/deis/registry): https://github.com/deis/registry/pull/55
  - [x] [deis/dockerbuilder](https://github.com/deis/dockerbuilder): https://github.com/deis/dockerbuilder/pull/68
  - [x] [deis/object-storage-cli](https://github.com/deis/object-storage-cli): https://github.com/deis/object-storage-cli/pull/14
  - [x] [deis/workflow](https://github.com/workflow): https://github.com/deis/workflow/pull/352
